DROP TABLE IF EXISTS AIRLINES;

CREATE OR REPLACE TABLE AIRLINES (
	IATA_CODE VARCHAR(2)
	,AIRLINE VARCHAR(28)
);


DROP TABLE IF EXISTS AIRPORTS;

CREATE OR REPLACE TABLE AIRPORTS (
	IATA_CODE VARCHAR(3)
	,AIRPORT VARCHAR(77)
	,CITY VARCHAR(30)
	,STATE VARCHAR(2)
	,COUNTRY VARCHAR(3)
	,LATITUDE DOUBLE
	,LONGITUDE DOUBLE
);


DROP TABLE IF EXISTS FLIGHTS;

CREATE OR REPLACE TABLE FLIGHTS (
	YEAR BIGINT
	,MONTH BIGINT
	,DAY BIGINT
	,DAY_OF_WEEK BIGINT
	,AIRLINE VARCHAR(2)
	,FLIGHT_NUMBER BIGINT
	,TAIL_NUMBER VARCHAR(6)
	,ORIGIN_AIRPORT VARCHAR(3)
	,DESTINATION_AIRPORT VARCHAR(3)
	,SCHEDULED_DEPARTURE BIGINT
	,DEPARTURE_TIME BIGINT
	,DEPARTURE_DELAY BIGINT
	,TAXI_OUT BIGINT
	,WHEELS_OFF BIGINT
	,SCHEDULED_TIME BIGINT
	,ELAPSED_TIME BIGINT
	,AIR_TIME BIGINT
	,DISTANCE BIGINT
	,WHEELS_ON BIGINT
	,TAXI_IN BIGINT
	,SCHEDULED_ARRIVAL BIGINT
	,ARRIVAL_TIME BIGINT
	,ARRIVAL_DELAY BIGINT
	,DIVERTED BIGINT
	,CANCELLED BIGINT
	,CANCELLATION_REASON VARCHAR(1)
	,AIR_SYSTEM_DELAY BIGINT
	,SECURITY_DELAY BIGINT
	,AIRLINE_DELAY BIGINT
	,LATE_AIRCRAFT_DELAY BIGINT
	,WEATHER_DELAY BIGINT
);